print('Programa que lê o preço de um produto e mostra seu novo preço, com 5% de desconto.')
print('-'*82)
preço = float(input('Digite o valor do produto: '))
novo = preço - (preço * 5 / 100)
print('O valor com desconto de 5% é {:.2f}'.format(novo))
